/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DAside: typeof import('vue-devui/aside/index.es.js')['Aside']
    DContent: typeof import('vue-devui/content/index.es.js')['Content']
    DFooter: typeof import('vue-devui/footer/index.es.js')['Footer']
    DHeader: typeof import('vue-devui/header/index.es.js')['Header']
    DLayout: typeof import('vue-devui/layout/index.es.js')['Layout']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
